### ISSUE TITLE
How do I install it? 

### ISSUE THREAD

**Issue by UltiRequiem** [skanehira/preview-markdown.vim#16]
I have tried with '[Plug](https://github.com/junegunn/vim-plug)', but it did not work ...

**Comment by richardbadman** [comment]
I use Plug and I got it to work; _(using Mac)_

1. Download the latest [MDR](https://github.com/MichaelMure/mdr) installed as required in the prerequisites
2. Move the binary to your bin directory and make it executable:
```shell
mv ~/Downloads/mdr_darwin_amd64 /usr/local/bin/mdr
chmod +x /usr/local/bin/mdr
```
3. In your `~/.vimrc` have the following _(make sure it's **before** `call plug#end()`)_
```
" Markdown preview
Plug 'skanehira/preview-markdown.vim'
```
4. Run `:PlugInstall` _(you'll have to write and quit, and then re-open vim)_

---

If you install a different `mdr` or want to make it display in a vertical pane _(defaults to horizontal)_, you'll add the following to your `~/.vimrc`

```
" Markdown preview
Plug 'skanehira/preview-markdown.vim'
let g:preview_markdown_viewer=path/to/your/custom/mdr
let g:preview_markdown_vertical=1
```

**Comment by UltiRequiem** [comment]
preview-markdown.vim: mdr not found, please install mdr
![image](https://user-images.githubusercontent.com/71897736/106344557-71379e00-6278-11eb-824d-095ec1dda903.png)
![image](https://user-images.githubusercontent.com/71897736/106344654-1783a380-6279-11eb-9dd5-9e695d5b0504.png)
And yes, all files have execution permissions ...
![image](https://user-images.githubusercontent.com/71897736/106344779-d63fc380-6279-11eb-89f7-26b31956c3e0.png)
![image](https://user-images.githubusercontent.com/71897736/106344787-de97fe80-6279-11eb-87ef-b58814ac42b8.png)

I'm using Ubuntu, and I download several just for testing, my laptop is amd64.
![image](https://user-images.githubusercontent.com/71897736/106344711-7517f000-6279-11eb-93b5-d4626e4a97aa.png)

**Comment by UltiRequiem** [comment]
My .vimrc file
![image](https://user-images.githubusercontent.com/71897736/106344834-20c14000-627a-11eb-84d7-b8954845fda1.png)

**Comment by skanehira** [comment]
@EliazBobadilla It seems like vim cannot found `mdr` from $PATH
What result execute bellow command?

```
:!which mdr
```

If vim can found `mdr`, result will be like bellow.

```
/home/skanehira/dev/go/bin/mdr
```

**Comment by UltiRequiem** [comment]
Watch:
https://user-images.githubusercontent.com/71897736/106372599-36e50400-633f-11eb-904d-3dcbcc4861d1.mp4

**Comment by skanehira** [comment]
It seems like your Vim can't found `mdr`
What return result in `:echo $PATH`?
If $PATH doesn't include path of mdr, I think Vim can't run `mdr`

**Comment by UltiRequiem** [comment]
> It seems like your Vim can't found `mdr`
> What return result in `:echo $PATH`?
> If $PATH doesn't include path of mdr, I think Vim can't run `mdr`

![image](https://user-images.githubusercontent.com/71897736/106478017-c6d99980-6476-11eb-93cc-234e546a00ab.png)

**Comment by UltiRequiem** [comment]
Now it works, now I use Arch btw
