### ISSUE TITLE
preview window in the left

### ISSUE THREAD

**Issue by georgemaxx** [skanehira/preview-markdown.vim#19]
when I press `:PreviewMarkdown` and enter, the preview window shows in the left, can I modify it to make it display in the right

**Comment by fedeoliv** [comment]
Same here. @skanehira do you have any hint to display it in the right?

**Comment by skanehira** [comment]
I'll support that will be like this :)

```vim
:PreviewMarkdown [left|right|top|bottom]
```

**Comment by fedeoliv** [comment]
Thank you @skanehira, it's working well for me :)

**Comment by skanehira** [comment]
I supported, please update plugin and check it :)
https://github.com/skanehira/preview-markdown.vim/pull/20

**Comment by georgemaxx** [comment]
@skanehira Thanks a lot, it works.
