### ISSUE TITLE
Neovim support?

### ISSUE THREAD

**Issue by kjuq** [skanehira/preview-markdown.vim#3]
Neovim fails to render the preview with the message; `preview-markdown.vim: this version doesn't support terminal`
Are you planning to support neovim?

**Comment by skanehira** [comment]
@kob4lt I'll support Neovim :+1:

**Comment by skanehira** [comment]
@kob4lt Supported Neovim in this PR :)
Please try it and let me know if doesn't work fine.
https://github.com/skanehira/preview-markdown.vim/pull/4
