### ISSUE TITLE
glow errors out with "Error: missing markdown source"

### ISSUE THREAD

**Issue by mtpereira** [skanehira/preview-markdown.vim#6]
Hi!

I've set up the plugin so that it uses `glow` (`let g:preview_markdown_parser = "glow"`) and when I run `:PreviewMarkdown` on a buffer with a `.md` file, it does open a new window and runs `glow`, but it errors out with:

> Error: missing markdown source

It feels like `preview_markdown#preview()` is not passing any file name to `glow`.

Am I doing something wrong?

Thank you so much for the plugin and for any help! :bowing_man:

**Comment by skanehira** [comment]
@mtpereira It's looks like preview-markdown.vim bug :cry: 
I'll check source..

**Comment by skanehira** [comment]
@mtpereira This bug looks like fixed.
Can you update and try agin?

**Comment by mtpereira** [comment]
Yes, it works now. Thanks! :bow:

**Comment by skanehira** [comment]
Thanks :)
