### ISSUE TITLE
Doesn't work on neovim

### ISSUE THREAD

**Issue by rbudiharso** [skanehira/preview-markdown.vim#7]
With neovim, when I call `:PreviewMarkdown` it error with `Undefined variable: opt` which I think is from this [line](https://github.com/skanehira/preview-markdown.vim/blob/master/autoload/preview_markdown.vim#L48)

After I remove the `opt` or define it with `let opt = {}` the error is `error while reading file: open /tmp/nvimv2tjpV/3.md: no such file or directory`

**Comment by jdonofrio728** [comment]
Ran into similar issues with this. The delete call in line 99 is executing which deletes the temp file causing the final error your seeing. You can comment that out which will get the the second window to render, but there are other issues still plaguing this on neovim.

**Comment by skanehira** [comment]
Sorry, I fixed this problem in ed0a2ee
Please update plugin and try again
