### ISSUE TITLE
Preview does not load in regular vim

### ISSUE THREAD

**Issue by aquatix** [skanehira/preview-markdown.vim#8]
When viewing a markdown file in vim, and doing the :PreviewMarkdown for a few weeks now I get this error:

```
Error detected while processing function preview_markdown#preview:
line   68:
E119: Not enough arguments for function: bufnr
E116: Invalid arguments for function term_getjob(bufnr())
```

Using vim 8.1.1401

The plugin used to work; I checked, the last commit working here is 13a8f21882334f0cd18164ae3ad516810591de28 After that, 3265c3e586511b1952d8c1770f07cbdf6c8f5f42 breaks it.

**Comment by skanehira** [comment]
@aquatix 
It's look like your vim version is old.
`bufnr()` is require argments before https://github.com/vim/vim/commit/a8eee21e75324d199acb1663cb5009e03014a13a

I supportted 8.1.1401 in fd2404df
Please update plugin and try again :)

**Comment by aquatix** [comment]
Yep, works again, thanks!

This vim version is from the currently latest Ubuntu (19.10), so 'old' is relative ;)
